server:
  port: 9090

spring:
  application:
    name: microservices-llm-security
  ai:
    mistralai:
      api-key: ${MISTRAL_API_KEY}
      chat:
        enabled: true
        options:
          model: mistral-small
          temperature: 0.7


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

